## CI for tbears

image: python:latest

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv -p /usr/bin/python3 venv
  - source venv/bin/activate
  - python -V
  - python -m pip install wheel
  
stages:
#   - test
  - build
#   - deploy

#test:
#   stage: test
#  script:
#  - python -m unittest
#  only:
#  - master

dist_wheel:
  stage: build
  script:
  - rm -rf build dist *.egg-info
  - python setup.py bdist_wheel
  - ls dist/
  artifacts:
    paths:
    - dist
  only:
  - master
  when: manual

# pages:
#   stage: deploy
#   script:
#   - pwd
#   - ls -al
#   - ls dist/
#   - cp -rf dist ../public
#   artifacts:
#     paths:
#     - public
#   only:
#   - master
